"""empty message

Revision ID: 021c960b1494
Revises: bf9e9bac7f40
Create Date: 2022-08-25 12:21:13.750968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021c960b1494'
down_revision = 'bf9e9bac7f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    # ### end Alembic commands ###
