"""empty message

Revision ID: 0543cd574f26
Revises: 021c960b1494
Create Date: 2022-08-25 12:22:04.546916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0543cd574f26'
down_revision = '021c960b1494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_session', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='unique')
    # ### end Alembic commands ###
