"""empty message

Revision ID: 1fab4e73a8ef
Revises: fb06a40a07e4
Create Date: 2022-08-29 12:02:04.249483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fab4e73a8ef'
down_revision = 'fb06a40a07e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_on')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
