"""empty message

Revision ID: 22df5a7960c7
Revises: 3e0824e9c08a
Create Date: 2022-09-02 10:28:45.190046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22df5a7960c7'
down_revision = '3e0824e9c08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_gender_gender_id_fkey', 'product_gender', type_='foreignkey')
    op.drop_constraint('product_gender_product_id_fkey', 'product_gender', type_='foreignkey')
    op.create_foreign_key(None, 'product_gender', 'genders', ['gender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_gender', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shoe_size_cm_product_data_product_data_id_fkey', 'shoe_size_cm_product_data', type_='foreignkey')
    op.drop_constraint('shoe_size_cm_product_data_shoe_size_id_fkey', 'shoe_size_cm_product_data', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_size_cm_product_data', 'product_data', ['product_data_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shoe_size_cm_product_data', 'shoe_sizes_cm', ['shoe_size_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shoe_size_eu_product_data_shoe_size_id_fkey', 'shoe_size_eu_product_data', type_='foreignkey')
    op.drop_constraint('shoe_size_eu_product_data_product_data_id_fkey', 'shoe_size_eu_product_data', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_size_eu_product_data', 'shoe_sizes_eu', ['shoe_size_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shoe_size_eu_product_data', 'product_data', ['product_data_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shoe_size_uk_product_data_shoe_size_id_fkey', 'shoe_size_uk_product_data', type_='foreignkey')
    op.drop_constraint('shoe_size_uk_product_data_product_data_id_fkey', 'shoe_size_uk_product_data', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_size_uk_product_data', 'product_data', ['product_data_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shoe_size_uk_product_data', 'shoe_sizes_uk', ['shoe_size_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shoe_size_us_product_data_product_data_id_fkey', 'shoe_size_us_product_data', type_='foreignkey')
    op.drop_constraint('shoe_size_us_product_data_shoe_size_id_fkey', 'shoe_size_us_product_data', type_='foreignkey')
    op.create_foreign_key(None, 'shoe_size_us_product_data', 'product_data', ['product_data_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shoe_size_us_product_data', 'shoe_sizes_us', ['shoe_size_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoe_size_us_product_data', type_='foreignkey')
    op.drop_constraint(None, 'shoe_size_us_product_data', type_='foreignkey')
    op.create_foreign_key('shoe_size_us_product_data_shoe_size_id_fkey', 'shoe_size_us_product_data', 'shoe_sizes_us', ['shoe_size_id'], ['id'])
    op.create_foreign_key('shoe_size_us_product_data_product_data_id_fkey', 'shoe_size_us_product_data', 'product_data', ['product_data_id'], ['id'])
    op.drop_constraint(None, 'shoe_size_uk_product_data', type_='foreignkey')
    op.drop_constraint(None, 'shoe_size_uk_product_data', type_='foreignkey')
    op.create_foreign_key('shoe_size_uk_product_data_product_data_id_fkey', 'shoe_size_uk_product_data', 'product_data', ['product_data_id'], ['id'])
    op.create_foreign_key('shoe_size_uk_product_data_shoe_size_id_fkey', 'shoe_size_uk_product_data', 'shoe_sizes_uk', ['shoe_size_id'], ['id'])
    op.drop_constraint(None, 'shoe_size_eu_product_data', type_='foreignkey')
    op.drop_constraint(None, 'shoe_size_eu_product_data', type_='foreignkey')
    op.create_foreign_key('shoe_size_eu_product_data_product_data_id_fkey', 'shoe_size_eu_product_data', 'product_data', ['product_data_id'], ['id'])
    op.create_foreign_key('shoe_size_eu_product_data_shoe_size_id_fkey', 'shoe_size_eu_product_data', 'shoe_sizes_eu', ['shoe_size_id'], ['id'])
    op.drop_constraint(None, 'shoe_size_cm_product_data', type_='foreignkey')
    op.drop_constraint(None, 'shoe_size_cm_product_data', type_='foreignkey')
    op.create_foreign_key('shoe_size_cm_product_data_shoe_size_id_fkey', 'shoe_size_cm_product_data', 'shoe_sizes_cm', ['shoe_size_id'], ['id'])
    op.create_foreign_key('shoe_size_cm_product_data_product_data_id_fkey', 'shoe_size_cm_product_data', 'product_data', ['product_data_id'], ['id'])
    op.drop_constraint(None, 'product_gender', type_='foreignkey')
    op.drop_constraint(None, 'product_gender', type_='foreignkey')
    op.create_foreign_key('product_gender_product_id_fkey', 'product_gender', 'products', ['product_id'], ['id'])
    op.create_foreign_key('product_gender_gender_id_fkey', 'product_gender', 'genders', ['gender_id'], ['id'])
    # ### end Alembic commands ###
