"""empty message

Revision ID: 298ad6399737
Revises: 686d15e24023
Create Date: 2022-08-21 00:04:38.958944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298ad6399737'
down_revision = '686d15e24023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('max_products', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'max_products')
    # ### end Alembic commands ###
