"""empty message

Revision ID: 4147613a9092
Revises: 1497d5c778de
Create Date: 2022-09-04 08:58:11.435709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4147613a9092'
down_revision = '1497d5c778de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('products_scraped', sa.Integer(), nullable=False),
    sa.Column('product_data_scraped', sa.Integer(), nullable=False),
    sa.Column('scrape_length_secs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapes')
    # ### end Alembic commands ###
