"""empty message

Revision ID: 686d15e24023
Revises: 8e73d6affab8
Create Date: 2022-08-18 00:02:11.194818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686d15e24023'
down_revision = '8e73d6affab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predefined_profile_filters', 'out_of_stock',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predefined_profile_filters', 'out_of_stock',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
