"""empty message

Revision ID: 8e73d6affab8
Revises: c5c71a4dcd0d
Create Date: 2022-08-17 23:56:11.443181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e73d6affab8'
down_revision = 'c5c71a4dcd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predefined_profile_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('percent_off', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('out_of_stock', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predefined_profile_filters_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['predefined_profile_filters_id'], ['predefined_profile_filters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predefined_profile_filters_shoe_size_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True),
    sa.Column('shoe_size_us_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predefined_profile_filters_id'], ['predefined_profile_filters.id'], ),
    sa.ForeignKeyConstraint(['shoe_size_us_id'], ['shoe_sizes_us.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('predefined_profile_filters_eshop', sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predefined_profile_filters_eshop', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.drop_column('predefined_profile_filters_eshop', 'predefined_profile_filters')
    op.add_column('predefined_profile_filters_gender', sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predefined_profile_filters_gender', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.drop_column('predefined_profile_filters_gender', 'predefined_profile_filters')
    op.add_column('predefined_profile_filters_shoe_size_cm', sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_cm', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.drop_column('predefined_profile_filters_shoe_size_cm', 'predefined_profile_filters')
    op.add_column('predefined_profile_filters_shoe_size_eu', sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_eu', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.drop_column('predefined_profile_filters_shoe_size_eu', 'predefined_profile_filters')
    op.add_column('predefined_profile_filters_shoe_size_uk', sa.Column('predefined_profile_filters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_uk', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.drop_column('predefined_profile_filters_shoe_size_uk', 'predefined_profile_filters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_profile_filters_shoe_size_uk', sa.Column('predefined_profile_filters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_uk', type_='foreignkey')
    op.drop_column('predefined_profile_filters_shoe_size_uk', 'predefined_profile_filters_id')
    op.add_column('predefined_profile_filters_shoe_size_eu', sa.Column('predefined_profile_filters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_eu', type_='foreignkey')
    op.drop_column('predefined_profile_filters_shoe_size_eu', 'predefined_profile_filters_id')
    op.add_column('predefined_profile_filters_shoe_size_cm', sa.Column('predefined_profile_filters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_cm', type_='foreignkey')
    op.drop_column('predefined_profile_filters_shoe_size_cm', 'predefined_profile_filters_id')
    op.add_column('predefined_profile_filters_gender', sa.Column('predefined_profile_filters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'predefined_profile_filters_gender', type_='foreignkey')
    op.drop_column('predefined_profile_filters_gender', 'predefined_profile_filters_id')
    op.add_column('predefined_profile_filters_eshop', sa.Column('predefined_profile_filters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'predefined_profile_filters_eshop', type_='foreignkey')
    op.drop_column('predefined_profile_filters_eshop', 'predefined_profile_filters_id')
    op.drop_table('predefined_profile_filters_shoe_size_us')
    op.drop_table('predefined_profile_filters_brand')
    op.drop_table('predefined_profile_filters')
    # ### end Alembic commands ###
