"""empty message

Revision ID: 9c2fe578f2e5
Revises: be11e6c0bd40
Create Date: 2022-08-21 00:06:18.736570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2fe578f2e5'
down_revision = 'be11e6c0bd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email_activated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_products', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('avatar_uri', sa.String(length=256), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('send_notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predefined_profile_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('percent_off', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('out_of_stock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'predefined_profile_filters_brand', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_eshop', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_gender', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_cm', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_eu', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_uk', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_us', 'predefined_profile_filters', ['predefined_profile_filters_id'], ['id'])
    op.create_foreign_key(None, 'profile_gender', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'profile_product', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_product', type_='foreignkey')
    op.drop_constraint(None, 'profile_gender', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_us', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_uk', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_eu', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_cm', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_gender', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_eshop', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_brand', type_='foreignkey')
    op.drop_table('predefined_profile_filters')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
