"""empty message

Revision ID: ba10fb19f911
Revises: 9c2fe578f2e5
Create Date: 2022-08-24 21:05:36.310267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba10fb19f911'
down_revision = '9c2fe578f2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###
