"""empty message

Revision ID: c5c71a4dcd0d
Revises: 79e9799b7475
Create Date: 2022-08-17 23:34:28.579592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c71a4dcd0d'
down_revision = '79e9799b7475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predefined_profile_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('percent_off', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'predefined_profile_filters_brand', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_eshop', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_gender', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_cm', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_eu', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_uk', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    op.create_foreign_key(None, 'predefined_profile_filters_shoe_size_us', 'predefined_profile_filters', ['predefined_profile_filters'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_us', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_uk', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_eu', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_shoe_size_cm', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_gender', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_eshop', type_='foreignkey')
    op.drop_constraint(None, 'predefined_profile_filters_brand', type_='foreignkey')
    op.drop_table('predefined_profile_filters')
    # ### end Alembic commands ###
