"""empty message

Revision ID: d9d45ef3daa8
Revises: 918f6473e7fa
Create Date: 2022-08-09 22:24:55.517597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d45ef3daa8'
down_revision = '918f6473e7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('avatar_uri', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'profile_gender', 'profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'profile_product', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_product', type_='foreignkey')
    op.drop_constraint(None, 'profile_gender', type_='foreignkey')
    op.drop_table('profiles')
    # ### end Alembic commands ###
